//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeSheetDBEntities : DbContext
    {
        public TimeSheetDBEntities()
            : base("name=TimeSheetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MapTaskState> MapTaskState { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectHistory> ProjectHistory { get; set; }
        public virtual DbSet<ProjectTask> ProjectTask { get; set; }
        public virtual DbSet<ProjectTaskUser> ProjectTaskUser { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskUserTime> TaskUserTime { get; set; }
        public virtual DbSet<VProjectHistory> VProjectHistory { get; set; }
        public virtual DbSet<VProjectTask> VProjectTask { get; set; }
        public virtual DbSet<VProjectTaskUser> VProjectTaskUser { get; set; }
        public virtual DbSet<VTaskTime> VTaskTime { get; set; }
        public virtual DbSet<TaskUserTimeHistory> TaskUserTimeHistory { get; set; }
    }
}
