//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Address = new HashSet<Address>();
            this.Invoice = new HashSet<Invoice>();
            this.Order = new HashSet<Order>();
            this.Production = new HashSet<Production>();
        }
    
        public int Customerid { get; set; }
        public string Customername { get; set; }
        public string TC_Customertypeid { get; set; }
        public string CO_Accountmanagerid { get; set; }
        public string Userid { get; set; }
        public string VATnumber { get; set; }
        public string TV_VATcodeid { get; set; }
        public string CD_Paymenttypeid { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Numbersupplinvoice { get; set; }
        public string OB_Invoicetextid { get; set; }
        public string Confirmation { get; set; }
        public string Linkid { get; set; }
        public Nullable<bool> Export { get; set; }
        public bool VAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
        public virtual Codespec Codespec2 { get; set; }
        public virtual Codespec Codespec3 { get; set; }
        public virtual Codespec Codespec4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
    }
}
