//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVMapLanguage
    {
        public long MapLanguageID { get; set; }
        public string DescFrench { get; set; }
        public string DescDutch { get; set; }
        public string DescEnglish { get; set; }
        public string DescGerman { get; set; }
        public bool Active { get; set; }
    }
}
