//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionToExport
    {
        public int ProductionToExportID { get; set; }
        public int Productionflyersid { get; set; }
        public string ArticleUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public string Status { get; set; }
        public bool ToExport { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string UIProjectID { get; set; }
    }
}
