//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediargusFTPExclude
    {
        public long MediargusFTPExcludeID { get; set; }
        public string DirectoryName { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
