//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessState
    {
        public int ProcessStateId { get; set; }
        public int MapModuleId { get; set; }
        public string JobProcess { get; set; }
        public Nullable<System.DateTime> ProcessStartTime { get; set; }
        public string ProcessState1 { get; set; }
        public Nullable<int> MaxAlert { get; set; }
    
        public virtual MapModule MapModule { get; set; }
    }
}
