//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTaskTime
    {
        public long TaskUserTimeID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProjectName { get; set; }
        public string TaskName { get; set; }
        public string UserName { get; set; }
        public long ProjectID { get; set; }
        public Nullable<long> ProjectTaskUserID { get; set; }
    }
}
