//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historystatistics
    {
        public int Historystatisticsid { get; set; }
        public int Publicationid { get; set; }
        public System.DateTime Statisticsdate { get; set; }
        public Nullable<int> Circulation { get; set; }
        public Nullable<int> Audience { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual Publication Publication { get; set; }
    }
}
