//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resource/buffer.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resource/folder.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("resource/timer.png")]


