//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordertotal
    {
        public int Ordertotalid { get; set; }
        public int Orderid { get; set; }
        public string PU_Publicationperiodicity { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int Articles { get; set; }
        public int Circulation { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Order Order { get; set; }
    }
}
