//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVJournalistDetail
    {
        public string Titre { get; set; }
        public string MapSubjectFR { get; set; }
        public string MapSubjectNL { get; set; }
        public string MapSubjectEN { get; set; }
        public string MapSubjectDE { get; set; }
        public long ContactID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
    }
}
