//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Ordersending = new HashSet<Ordersending>();
            this.Order = new HashSet<Order>();
            this.Subscription = new HashSet<Subscription>();
        }
    
        public int Addressid { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<int> Publisherid { get; set; }
        public string TA_Addresstypeid { get; set; }
        public string GE_Customercategoryid { get; set; }
        public string LA_Languageid { get; set; }
        public string TI_Contactfunctionid { get; set; }
        public string Contactname { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Bus { get; set; }
        public string Postalcode { get; set; }
        public string City { get; set; }
        public string PY_Countryid { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string GSM { get; set; }
        public string Companyname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordersending> Ordersending { get; set; }
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
        public virtual Codespec Codespec2 { get; set; }
        public virtual Codespec Codespec3 { get; set; }
        public virtual Codespec Codespec4 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscription { get; set; }
    }
}
