//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewForArchives
    {
        public int Publicationid { get; set; }
        public string Publicationname { get; set; }
        public string LA_Languageid { get; set; }
        public string PU_Publicationperiodicityid { get; set; }
        public string ME_Mediatypeid { get; set; }
        public string Linkid { get; set; }
    }
}
