//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeywordLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeywordLine()
        {
            this.KeywordCondition = new HashSet<KeywordCondition>();
        }
    
        public long KeywordLineID { get; set; }
        public long KeywordGroupID { get; set; }
        public string KeywordName { get; set; }
        public bool KeywordInclude { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public bool KeywordAllKeywords { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeywordCondition> KeywordCondition { get; set; }
        public virtual KeywordGroup KeywordGroup { get; set; }
    }
}
