//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapTaskState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MapTaskState()
        {
            this.ProjectTaskUser = new HashSet<ProjectTaskUser>();
        }
    
        public long MapTaskStateID { get; set; }
        public string MapTaskStateName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTaskUser> ProjectTaskUser { get; set; }
    }
}
