//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MapModule()
        {
            this.ProcessState = new HashSet<ProcessState>();
        }
    
        public int MapModuleID { get; set; }
        public string ModuleName { get; set; }
        public string Comment { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> TimeLife { get; set; }
        public string MachineName { get; set; }
        public bool IsService { get; set; }
        public bool Active { get; set; }
        public int SortIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessState> ProcessState { get; set; }
    }
}
