//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mediargus
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public string Sourcename { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
