//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveFilesDetail
    {
        public int ParameterID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Filter { get; set; }
        public bool Subfolders { get; set; }
        public bool Active { get; set; }
        public bool DeleteEmptySubfolders { get; set; }
        public int Timing { get; set; }
        public Nullable<int> DaysToKeep { get; set; }
    }
}
