//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewbaseServices
    {
        public long NewbaseServiceID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> NewbaseServerID { get; set; }
        public bool IsOnError { get; set; }
        public bool IsActive { get; set; }
        public bool SendMail { get; set; }
    
        public virtual NewbaseServers NewbaseServers { get; set; }
    }
}
