//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UICustomerMail
    {
        public long UICustomerMailID { get; set; }
        public string Customer { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
    }
}
