//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCleanFiles
    {
        public int APMDBID { get; set; }
        public string ParamName { get; set; }
        public string FolderPath { get; set; }
        public string KeepLastUnit { get; set; }
        public int KeepLastValue { get; set; }
        public string Filter { get; set; }
        public bool DeleteSubfolders { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
