//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Invoicedetail = new HashSet<Invoicedetail>();
        }
    
        public int Invoiceid { get; set; }
        public string PA_Ownerid { get; set; }
        public string IT_Invoicetypeid { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public Nullable<int> Invoicenumber { get; set; }
        public Nullable<int> Customerid { get; set; }
        public string Customerreference { get; set; }
        public bool Approved { get; set; }
        public System.DateTime Expirydate { get; set; }
        public string Communication { get; set; }
        public string Remark { get; set; }
        public bool Export { get; set; }
        public bool Email { get; set; }
        public bool EmailCustomer { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoicedetail> Invoicedetail { get; set; }
    }
}
