//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewbaseServers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewbaseServers()
        {
            this.NewbaseServices = new HashSet<NewbaseServices>();
        }
    
        public int NewbaseServerID { get; set; }
        public string MachineName { get; set; }
        public bool IsOnError { get; set; }
        public bool IsActive { get; set; }
        public bool SendMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewbaseServices> NewbaseServices { get; set; }
    }
}
