//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVContactMedia
    {
        public long ContactMediaID { get; set; }
        public long ContactID { get; set; }
        public long MediaID { get; set; }
        public Nullable<long> MapCountryID { get; set; }
        public string ContactTitle { get; set; }
    }
}
