//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCustomersInternational
    {
        public int Customerid { get; set; }
        public string Customername { get; set; }
        public string Contactname { get; set; }
        public string Langue { get; set; }
        public string Email { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Bus { get; set; }
        public string Postalcode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int Orderid { get; set; }
        public string Ordername { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
    }
}
