//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTaskUser()
        {
            this.TaskUserTime = new HashSet<TaskUserTime>();
        }
    
        public long ProjectTaskUserID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> TaskID { get; set; }
        public Nullable<System.DateTime> StartTask { get; set; }
        public Nullable<System.DateTime> EndTask { get; set; }
        public Nullable<float> ExecutionTime { get; set; }
        public Nullable<long> MapTaskStateID { get; set; }
        public string UserName { get; set; }
    
        public virtual MapTaskState MapTaskState { get; set; }
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskUserTime> TaskUserTime { get; set; }
    }
}
