//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectHistory
    {
        public long ProjectHistoryID { get; set; }
        public long ProjectID { get; set; }
        public Nullable<float> LastTime { get; set; }
        public Nullable<float> NewTime { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
