//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProjectTaskUser
    {
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> TaskID { get; set; }
        public string ProjectName { get; set; }
        public string TaskName { get; set; }
        public string MapTaskStateName { get; set; }
        public Nullable<System.DateTime> StartTask { get; set; }
        public Nullable<System.DateTime> EndTask { get; set; }
        public Nullable<float> ExecutionTime { get; set; }
        public string UserName { get; set; }
        public long ProjectTaskUserID { get; set; }
        public long MapTaskStateID { get; set; }
    }
}
