//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTotalArticles
    {
        public string OrderID { get; set; }
        public System.DateTime Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string PU_Publicationperiodicity { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int Articles { get; set; }
        public int Circulation { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public Nullable<int> Codeorder { get; set; }
        public string GroupFR { get; set; }
        public string GroupNL { get; set; }
        public string GroupEN { get; set; }
        public string GroupGE { get; set; }
    }
}
