//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocialMediaType()
        {
            this.SocialMediaArticle = new HashSet<SocialMediaArticle>();
        }
    
        public string MediaType { get; set; }
        public int PublicationId { get; set; }
        public string LogoPath { get; set; }
        public int MapMediaTypeID { get; set; }
        public string SourceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialMediaArticle> SocialMediaArticle { get; set; }
    }
}
