//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVMediaFigureAll
    {
        public long MediaFigureAllID { get; set; }
        public long MediaID { get; set; }
        public Nullable<int> JumbopilotID { get; set; }
        public Nullable<int> MediascoreID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> MapWeekdayUK { get; set; }
        public Nullable<int> Circulation { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Total_Audience { get; set; }
        public Nullable<decimal> C04_Audience { get; set; }
        public Nullable<decimal> C04_Percentage { get; set; }
        public Nullable<decimal> C12_Audience { get; set; }
        public Nullable<decimal> C12_Percentage { get; set; }
        public Nullable<decimal> Ho12_Audience { get; set; }
        public Nullable<decimal> Ho12_Percentage { get; set; }
        public Nullable<decimal> Fe12_Audience { get; set; }
        public Nullable<decimal> Fe12_Percentage { get; set; }
        public Nullable<decimal> C12SG1_2_Audience { get; set; }
        public Nullable<decimal> C12SG1_2_Percentage { get; set; }
        public Nullable<decimal> C12SG3_4_Audience { get; set; }
        public Nullable<decimal> C12SG3_4_Percentage { get; set; }
        public Nullable<decimal> C12SG5_6_Audience { get; set; }
        public Nullable<decimal> C12SG5_6_Percentage { get; set; }
        public Nullable<decimal> C12SG7_8_Audience { get; set; }
        public Nullable<decimal> C12SG7_8_Percentage { get; set; }
        public Nullable<decimal> C12_34_Audience { get; set; }
        public Nullable<decimal> C12_34_Percentage { get; set; }
        public Nullable<decimal> C35_54_Audience { get; set; }
        public Nullable<decimal> C35_54_Percentage { get; set; }
        public Nullable<decimal> C55_Audience { get; set; }
        public Nullable<decimal> C55_Percentage { get; set; }
        public Nullable<decimal> C15_Audience { get; set; }
        public Nullable<decimal> C15_Percentage { get; set; }
        public Nullable<decimal> C18_44_Audience { get; set; }
        public Nullable<decimal> C18_44_Percentage { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> FrmtLength { get; set; }
        public Nullable<short> FrmtWidth { get; set; }
    }
}
