//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVPublicationGroup
    {
        public long Publicationid { get; set; }
        public string Publicationname { get; set; }
        public string Name { get; set; }
        public Nullable<long> Publicationgroupid { get; set; }
    }
}
