//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int Articleid { get; set; }
        public int Deliveryid { get; set; }
        public string ArticleNo { get; set; }
        public string ArticleTitle { get; set; }
        public Nullable<long> ArticleSize { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public string Linkid { get; set; }
        public Nullable<System.DateTime> SendingDate { get; set; }
        public string Page { get; set; }
        public Nullable<int> TotalPages { get; set; }
        public string ArticleFile { get; set; }
        public string SS_Status { get; set; }
        public Nullable<bool> ForcedAsTest { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
        public Nullable<int> DBS_Id { get; set; }
        public string EvalId { get; set; }
        public Nullable<System.DateTime> MailingDate { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
