//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoLog
    {
        public long AutoLogID { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public string hostname { get; set; }
        public string net_library { get; set; }
        public string net_address { get; set; }
        public string client_net_address { get; set; }
        public string databefore { get; set; }
        public string dataafter { get; set; }
    }
}
