//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codetype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codetype()
        {
            this.Codespec = new HashSet<Codespec>();
        }
    
        public string Codetypeid { get; set; }
        public string Descriptionfrench { get; set; }
        public string Descriptiondutch { get; set; }
        public string Descriptionenglish { get; set; }
        public string Descriptiongerman { get; set; }
        public Nullable<System.DateTime> Inactivedate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codespec> Codespec { get; set; }
    }
}
