//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesendTemplate
    {
        public int FilesendTemplateid { get; set; }
        public string TemplateName { get; set; }
        public string Address { get; set; }
        public string Directory { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Passivemode { get; set; }
        public bool Delayed { get; set; }
        public string DelayedHour { get; set; }
        public bool Sendxml { get; set; }
        public bool Sendpdf { get; set; }
        public bool Sendemptyfile { get; set; }
        public string Emptyfilename { get; set; }
        public Nullable<int> XMLtemplateid { get; set; }
        public bool Compression { get; set; }
        public int Deliverymethod { get; set; }
        public bool Active { get; set; }
    }
}
