//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicedetailsending
    {
        public int Invoicedetailsendingid { get; set; }
        public int Invoicedetailid { get; set; }
        public string TE_Sendingtypeid { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Invoicedetail Invoicedetail { get; set; }
        public virtual Invoicedetailsending Invoicedetailsending1 { get; set; }
        public virtual Invoicedetailsending Invoicedetailsending2 { get; set; }
    }
}
