//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logdata
    {
        public int Logdataid { get; set; }
        public string Table { get; set; }
        public System.DateTime Date { get; set; }
        public string Userid { get; set; }
        public string Databefore { get; set; }
        public string Dataafter { get; set; }
    }
}
