//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuxipressJumboPilotEntities : DbContext
    {
        public AuxipressJumboPilotEntities()
            : base("name=AuxipressJumboPilotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<AutoLog> AutoLog { get; set; }
        public virtual DbSet<BADOrdersending> BADOrdersending { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<Codespec> Codespec { get; set; }
        public virtual DbSet<Codetype> Codetype { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Deliverysubject> Deliverysubject { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<EfficyContact> EfficyContact { get; set; }
        public virtual DbSet<EfficyProduct> EfficyProduct { get; set; }
        public virtual DbSet<FilesendTemplate> FilesendTemplate { get; set; }
        public virtual DbSet<Historystatistics> Historystatistics { get; set; }
        public virtual DbSet<Holiday> Holiday { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Invoicedetail> Invoicedetail { get; set; }
        public virtual DbSet<Invoicedetailsending> Invoicedetailsending { get; set; }
        public virtual DbSet<Keyword> Keyword { get; set; }
        public virtual DbSet<KeywordCondition> KeywordCondition { get; set; }
        public virtual DbSet<KeywordGroup> KeywordGroup { get; set; }
        public virtual DbSet<KeywordLine> KeywordLine { get; set; }
        public virtual DbSet<Logdata> Logdata { get; set; }
        public virtual DbSet<MapXMLtemplate> MapXMLtemplate { get; set; }
        public virtual DbSet<MediaFigureAll> MediaFigureAll { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderFileMove> OrderFileMove { get; set; }
        public virtual DbSet<Orderfilesend> Orderfilesend { get; set; }
        public virtual DbSet<OrderIdAsText> OrderIdAsText { get; set; }
        public virtual DbSet<Orderlink> Orderlink { get; set; }
        public virtual DbSet<Ordersending> Ordersending { get; set; }
        public virtual DbSet<Ordersendingschedule> Ordersendingschedule { get; set; }
        public virtual DbSet<Ordersubscription> Ordersubscription { get; set; }
        public virtual DbSet<Ordersubscriptionschedule> Ordersubscriptionschedule { get; set; }
        public virtual DbSet<Ordertotal> Ordertotal { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Period> Period { get; set; }
        public virtual DbSet<Planning> Planning { get; set; }
        public virtual DbSet<Postalcode> Postalcode { get; set; }
        public virtual DbSet<PressReviewLabel> PressReviewLabel { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<Productionflyers> Productionflyers { get; set; }
        public virtual DbSet<Productionsending> Productionsending { get; set; }
        public virtual DbSet<Productionsendingtill20150101> Productionsendingtill20150101 { get; set; }
        public virtual DbSet<Productiontill20150101> Productiontill20150101 { get; set; }
        public virtual DbSet<ProductionToExport> ProductionToExport { get; set; }
        public virtual DbSet<Producttypegroup> Producttypegroup { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<Publicationgroup> Publicationgroup { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<Royalty> Royalty { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Sendingprice> Sendingprice { get; set; }
        public virtual DbSet<SocialMediaArticle> SocialMediaArticle { get; set; }
        public virtual DbSet<SocialMediaReport> SocialMediaReport { get; set; }
        public virtual DbSet<SocialMediaReportType> SocialMediaReportType { get; set; }
        public virtual DbSet<SocialMediaTempOrder> SocialMediaTempOrder { get; set; }
        public virtual DbSet<SocialMediaType> SocialMediaType { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Systemparameter> Systemparameter { get; set; }
        public virtual DbSet<Tariff> Tariff { get; set; }
        public virtual DbSet<TempNewID> TempNewID { get; set; }
        public virtual DbSet<TP_AEXCLURE> TP_AEXCLURE { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Userlogonhistory> Userlogonhistory { get; set; }
        public virtual DbSet<Userorder> Userorder { get; set; }
        public virtual DbSet<AP_EncMan> AP_EncMan { get; set; }
        public virtual DbSet<AP_Retours> AP_Retours { get; set; }
        public virtual DbSet<ExportToNewbase> ExportToNewbase { get; set; }
        public virtual DbSet<Filtre_Pays> Filtre_Pays { get; set; }
        public virtual DbSet<Invoicenumber> Invoicenumber { get; set; }
        public virtual DbSet<Orderfilesend2> Orderfilesend2 { get; set; }
        public virtual DbSet<APVContact> APVContact { get; set; }
        public virtual DbSet<APVContactMedia> APVContactMedia { get; set; }
        public virtual DbSet<APVContactSubject> APVContactSubject { get; set; }
        public virtual DbSet<APVJournalistDetail> APVJournalistDetail { get; set; }
        public virtual DbSet<APVMapCountry> APVMapCountry { get; set; }
        public virtual DbSet<APVMapLanguage> APVMapLanguage { get; set; }
        public virtual DbSet<APVMedia> APVMedia { get; set; }
        public virtual DbSet<APVMediaFigure> APVMediaFigure { get; set; }
        public virtual DbSet<APVMediaFigureAll> APVMediaFigureAll { get; set; }
        public virtual DbSet<APVMediaGroup> APVMediaGroup { get; set; }
        public virtual DbSet<APVMediaLanguage> APVMediaLanguage { get; set; }
        public virtual DbSet<APVPublicationGroup> APVPublicationGroup { get; set; }
        public virtual DbSet<APVUser> APVUser { get; set; }
        public virtual DbSet<Facturation_Fred> Facturation_Fred { get; set; }
        public virtual DbSet<Tests_Fred> Tests_Fred { get; set; }
        public virtual DbSet<VActiveOrders> VActiveOrders { get; set; }
        public virtual DbSet<VAddress> VAddress { get; set; }
        public virtual DbSet<VArticlesToSend> VArticlesToSend { get; set; }
        public virtual DbSet<VBaroStats> VBaroStats { get; set; }
        public virtual DbSet<VCustomers> VCustomers { get; set; }
        public virtual DbSet<VCustomersDetails> VCustomersDetails { get; set; }
        public virtual DbSet<VCustomersInt> VCustomersInt { get; set; }
        public virtual DbSet<VCustomersInternational> VCustomersInternational { get; set; }
        public virtual DbSet<VCustomersInternationalDetails> VCustomersInternationalDetails { get; set; }
        public virtual DbSet<VCustWithActiveOrders> VCustWithActiveOrders { get; set; }
        public virtual DbSet<VFIBEPExport> VFIBEPExport { get; set; }
        public virtual DbSet<viewAmount> viewAmount { get; set; }
        public virtual DbSet<ViewCustomers> ViewCustomers { get; set; }
        public virtual DbSet<ViewForArchives> ViewForArchives { get; set; }
        public virtual DbSet<viewOrderName> viewOrderName { get; set; }
        public virtual DbSet<ViewProduction> ViewProduction { get; set; }
        public virtual DbSet<ViewTotalArticles> ViewTotalArticles { get; set; }
        public virtual DbSet<VKeywords> VKeywords { get; set; }
        public virtual DbSet<VNewBaseRubric> VNewBaseRubric { get; set; }
        public virtual DbSet<VOrderAdresses> VOrderAdresses { get; set; }
        public virtual DbSet<VOrderFileMvList> VOrderFileMvList { get; set; }
        public virtual DbSet<VOrders> VOrders { get; set; }
        public virtual DbSet<VOrdersEnd> VOrdersEnd { get; set; }
        public virtual DbSet<VOrderSendingDetails> VOrderSendingDetails { get; set; }
        public virtual DbSet<VOrdersEndSubscription> VOrdersEndSubscription { get; set; }
        public virtual DbSet<VOrdersRTV> VOrdersRTV { get; set; }
        public virtual DbSet<VOrdersWeb> VOrdersWeb { get; set; }
        public virtual DbSet<VProductionFlyers> VProductionFlyers { get; set; }
        public virtual DbSet<vw_aspnet_Applications> vw_aspnet_Applications { get; set; }
        public virtual DbSet<vw_aspnet_MembershipUsers> vw_aspnet_MembershipUsers { get; set; }
        public virtual DbSet<vw_aspnet_Profiles> vw_aspnet_Profiles { get; set; }
        public virtual DbSet<vw_aspnet_Roles> vw_aspnet_Roles { get; set; }
        public virtual DbSet<vw_aspnet_Users> vw_aspnet_Users { get; set; }
        public virtual DbSet<vw_aspnet_UsersInRoles> vw_aspnet_UsersInRoles { get; set; }
        public virtual DbSet<vw_aspnet_WebPartState_Paths> vw_aspnet_WebPartState_Paths { get; set; }
        public virtual DbSet<vw_aspnet_WebPartState_Shared> vw_aspnet_WebPartState_Shared { get; set; }
        public virtual DbSet<vw_aspnet_WebPartState_User> vw_aspnet_WebPartState_User { get; set; }
    }
}
