//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordersending
    {
        public int Ordersendingid { get; set; }
        public int Ordersubscriptionid { get; set; }
        public string TP_Producttypeid { get; set; }
        public string TE_Sendingtypeid { get; set; }
        public int Addressid { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
        public virtual Ordersubscription Ordersubscription { get; set; }
    }
}
