//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning
    {
        public int Planningid { get; set; }
        public Nullable<int> Deliveryid { get; set; }
        public Nullable<int> CLDay { get; set; }
        public string WD_Weekday { get; set; }
        public bool Fixedhours { get; set; }
        public string Listhours { get; set; }
        public string StartHour { get; set; }
        public Nullable<int> Interval { get; set; }
        public string EndHour { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
