//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postalcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postalcode()
        {
            this.Postalcode11 = new HashSet<Postalcode>();
        }
    
        public int Postalcodeid { get; set; }
        public string Postalcode1 { get; set; }
        public string City { get; set; }
        public int Parentpostalcodeid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postalcode> Postalcode11 { get; set; }
        public virtual Postalcode Postalcode2 { get; set; }
    }
}
