//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressReviewLabel
    {
        public int LabelID { get; set; }
        public string PressReview { get; set; }
        public string TOC { get; set; }
        public string Page { get; set; }
        public string LA_Languageid { get; set; }
    }
}
