//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.Historystatistics = new HashSet<Historystatistics>();
            this.Production = new HashSet<Production>();
            this.Productionflyers = new HashSet<Productionflyers>();
            this.Publication1 = new HashSet<Publication>();
            this.Royalty = new HashSet<Royalty>();
            this.Subscription = new HashSet<Subscription>();
            this.Publicationgroup = new HashSet<Publicationgroup>();
            this.Codespec7 = new HashSet<Codespec>();
        }
    
        public int Publicationid { get; set; }
        public string Publicationname { get; set; }
        public Nullable<int> Parentpublicationid { get; set; }
        public string PU_Publicationperiodicityid { get; set; }
        public bool Active { get; set; }
        public string ME_Mediatypeid { get; set; }
        public Nullable<int> Receivedcopies { get; set; }
        public int Publisherid { get; set; }
        public string FO_Formatid { get; set; }
        public Nullable<int> Pages { get; set; }
        public bool Morninginfo { get; set; }
        public string CP_Categoryid { get; set; }
        public string Responsible { get; set; }
        public string CF_Invoicecategoryid { get; set; }
        public string Linkid { get; set; }
        public bool Digitalrights { get; set; }
        public Nullable<int> Priority { get; set; }
        public string PY_Countryid { get; set; }
        public string CA_Calendartypeid { get; set; }
        public bool Export { get; set; }
        public string Website { get; set; }
        public bool MissingLogo { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
        public virtual Codespec Codespec2 { get; set; }
        public virtual Codespec Codespec3 { get; set; }
        public virtual Codespec Codespec4 { get; set; }
        public virtual Codespec Codespec5 { get; set; }
        public virtual Codespec Codespec6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historystatistics> Historystatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productionflyers> Productionflyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publication1 { get; set; }
        public virtual Publication Publication2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Royalty> Royalty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscription { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publicationgroup> Publicationgroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codespec> Codespec7 { get; set; }
    }
}
