//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaArticle
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string URL { get; set; }
        public Nullable<double> QueryRelevance { get; set; }
        public string TopicFilter { get; set; }
        public Nullable<System.DateTime> PublishedTime { get; set; }
        public Nullable<System.DateTime> IndexedTime { get; set; }
        public string MediaType { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string Author { get; set; }
        public string Title { get; set; }
        public string Snippet { get; set; }
        public bool HasImage { get; set; }
        public string Sentiment { get; set; }
        public bool Important { get; set; }
        public string Tags { get; set; }
        public string Score { get; set; }
        public Nullable<int> CommentsCount { get; set; }
        public Nullable<int> ViewsCount { get; set; }
        public Nullable<int> TweetsCount { get; set; }
        public Nullable<int> FacebookSharesCount { get; set; }
        public Nullable<int> FacebookLikesCount { get; set; }
        public string SourceDomain { get; set; }
        public string SourceHost { get; set; }
        public string SourceCountry { get; set; }
        public Nullable<int> SourceStars { get; set; }
        public Nullable<bool> SourceFavorite { get; set; }
        public string SourceRank { get; set; }
        public Nullable<long> SourceArticlesCount { get; set; }
        public Nullable<long> SourceViewsCount { get; set; }
        public Nullable<long> SourceTweetsCount { get; set; }
        public Nullable<long> SourceTwitterFollowersCount { get; set; }
        public Nullable<long> SourceFacebookSharesCount { get; set; }
        public Nullable<long> SourceFacebookLikesCount { get; set; }
        public Nullable<long> SourceFacebookFriendsCount { get; set; }
        public bool SentToCustomer { get; set; }
        public bool Exported { get; set; }
        public Nullable<System.DateTime> ImportTime { get; set; }
        public Nullable<long> Reach { get; set; }
        public string AuthorCountry { get; set; }
        public string AuthorGender { get; set; }
        public Nullable<int> SourceFacebookFollowers { get; set; }
        public Nullable<int> ArticleTwitterRetweets { get; set; }
        public Nullable<int> Engagement { get; set; }
        public string AuthorImage { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SocialMediaType SocialMediaType { get; set; }
    }
}
