//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        public int Tariffid { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public bool Variable { get; set; }
        public string TP_Producttypeid { get; set; }
        public string TR_Tariffplanid { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
    }
}
