//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Userid { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Logonid { get; set; }
        public string Password { get; set; }
        public string LA_Languageid { get; set; }
        public string UP_Userprofileid { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
    }
}
