//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VArticlesToSend
    {
        public string Customername { get; set; }
        public string Ordername { get; set; }
        public int Orderid { get; set; }
        public string ArticleNo { get; set; }
        public string EvalId { get; set; }
        public string Publicationname { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public string ArticleTitle { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
        public string SS_Status { get; set; }
    }
}
