//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBaroStats
    {
        public int Productionid { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public string Usernamecutter { get; set; }
        public string TP_Producttypeid { get; set; }
        public int Invoiceid { get; set; }
        public bool Approved { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Descriptionfrench { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
    }
}
