//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCustomersDetails
    {
        public int Customerid { get; set; }
        public string Customername { get; set; }
        public string Customertype { get; set; }
        public string Userid { get; set; }
        public string Accountmanagerid { get; set; }
        public string VATcodeid { get; set; }
        public string VATnumber { get; set; }
        public string Paymenttypeid { get; set; }
        public string Invoicetextid { get; set; }
        public string Confirmation { get; set; }
        public bool VAT { get; set; }
        public Nullable<int> Orderid { get; set; }
        public string Ordername { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Ordertext { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Internal { get; set; }
        public string Contactname { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> EmailCustomer { get; set; }
        public string OrderInvoicetextid { get; set; }
        public string Ownerid { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<System.DateTime> Nextinvoicedate { get; set; }
        public Nullable<bool> Inclusive { get; set; }
        public string Tariffplanid { get; set; }
    }
}
