//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFIBEPExport
    {
        public int Productionflyersid { get; set; }
        public string Customername { get; set; }
        public int Customerid { get; set; }
        public int Orderid { get; set; }
        public string Ordername { get; set; }
        public string Articleno { get; set; }
        public Nullable<System.DateTime> Publicationdate { get; set; }
        public Nullable<int> AVE { get; set; }
        public string AVECurrency { get; set; }
        public Nullable<int> Publicationid { get; set; }
        public Nullable<long> ContactID { get; set; }
        public string Articlepagenumber { get; set; }
        public string Articletitle { get; set; }
        public string Resume { get; set; }
        public string Languageid { get; set; }
        public string PDFLink { get; set; }
    }
}
