//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProduction
    {
        public Nullable<int> Orderid { get; set; }
        public Nullable<System.DateTime> Publicationdate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ME_Mediatypeid { get; set; }
        public string Descriptionfrench { get; set; }
        public string Descriptiondutch { get; set; }
        public string Descriptionenglish { get; set; }
        public string Descriptiongerman { get; set; }
        public string Codetypeid { get; set; }
        public Nullable<int> Codeorder { get; set; }
    }
}
