//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKeywords
    {
        public int Orderid { get; set; }
        public long KeywordGroupID { get; set; }
        public string LA_Languageid { get; set; }
        public string LanguageName { get; set; }
        public Nullable<int> NbOfKeywords { get; set; }
        public long KeywordLineID { get; set; }
        public string KeywordName { get; set; }
        public Nullable<bool> KeywordInclude { get; set; }
        public Nullable<int> NbOfConditions { get; set; }
        public string KC_ConditionTypeid { get; set; }
        public string ConditionName { get; set; }
        public string KeywordConditionName { get; set; }
        public Nullable<int> NbOfWords { get; set; }
        public long KeywordConditionID { get; set; }
        public Nullable<int> ListOrder1 { get; set; }
        public Nullable<int> ListOrder2 { get; set; }
        public Nullable<int> ListOrder3 { get; set; }
        public string KT_Typeid { get; set; }
        public string KeywordRTVTitle { get; set; }
        public Nullable<bool> KeywordAllKeywords { get; set; }
    }
}
