//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOrdersEndSubscription
    {
        public string Client { get; set; }
        public int CustID { get; set; }
        public string Secteur { get; set; }
        public string Commande { get; set; }
        public int Orderid { get; set; }
        public string Owner { get; set; }
        public string Commercial { get; set; }
        public string Produit { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<System.DateTime> Date_de_dernier_renouvellement { get; set; }
        public Nullable<System.DateTime> Date_de_fin { get; set; }
        public string Contactname { get; set; }
        public string Fonction { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Bus { get; set; }
        public string Postalcode { get; set; }
        public string City { get; set; }
        public string Pays { get; set; }
        public string Langue { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string GSM { get; set; }
        public string Companyname { get; set; }
    }
}
