//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOrderAdresses
    {
        public int Orderid { get; set; }
        public string Addresstype { get; set; }
        public string Contactname { get; set; }
        public string Contactfunction { get; set; }
        public string Language { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Bus { get; set; }
        public string Postalcode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string GSM { get; set; }
        public string TA_Addresstypeid { get; set; }
    }
}
