//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.Address = new HashSet<Address>();
        }
    
        public int Subscriptionid { get; set; }
        public string Subscriptionname { get; set; }
        public Nullable<int> Publicationid { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime Enddate { get; set; }
        public decimal Price { get; set; }
        public string Email { get; set; }
        public bool Cancelmail { get; set; }
        public string PA_Ownerid { get; set; }
        public Nullable<System.DateTime> Renewdate { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Publication Publication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
    }
}
