//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturation_Fred
    {
        public string Customername { get; set; }
        public string Ordername { get; set; }
        public string TypeF { get; set; }
        public Nullable<int> Invoicenumber { get; set; }
        public string DT { get; set; }
        public string PR { get; set; }
        public string TP { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Produits { get; set; }
        public Nullable<double> Envois { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public bool Approved { get; set; }
        public string Extracostdescription { get; set; }
        public string SE { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public Nullable<double> CustDiscount { get; set; }
        public Nullable<double> OrderDiscount { get; set; }
        public string PA_Ownerid { get; set; }
        public int Customerid { get; set; }
        public string CustomerType { get; set; }
        public Nullable<int> Orderid { get; set; }
    }
}
