//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Royalty
    {
        public int Royaltyid { get; set; }
        public int Publicationid { get; set; }
        public decimal Auxipressroyalty { get; set; }
        public decimal Customerroyalty { get; set; }
        public string TE_Sendingtypeid { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
