//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPDB.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternationalDir
    {
        public long InternationalDirID { get; set; }
        public string SupplierName { get; set; }
        public string Directory { get; set; }
        public string FilePrefix { get; set; }
        public bool Active { get; set; }
    }
}
