//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderFileMove = new HashSet<OrderFileMove>();
            this.Orderfilesend = new HashSet<Orderfilesend>();
            this.OrderIdAsText = new HashSet<OrderIdAsText>();
            this.SocialMediaArticle = new HashSet<SocialMediaArticle>();
            this.Ordersendingschedule = new HashSet<Ordersendingschedule>();
            this.Ordersubscription = new HashSet<Ordersubscription>();
            this.Ordertotal = new HashSet<Ordertotal>();
            this.Production = new HashSet<Production>();
            this.Productionflyers = new HashSet<Productionflyers>();
            this.Userorder = new HashSet<Userorder>();
            this.Address = new HashSet<Address>();
            this.SocialMediaReport = new HashSet<SocialMediaReport>();
        }
    
        public int Orderid { get; set; }
        public string Ordername { get; set; }
        public int Customerid { get; set; }
        public bool Active { get; set; }
        public bool Export { get; set; }
        public System.DateTime Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Ordertext { get; set; }
        public string Remark { get; set; }
        public bool Shippingblocked { get; set; }
        public Nullable<int> Discount { get; set; }
        public string OB_Invoicetextid { get; set; }
        public Nullable<int> Groupnumber { get; set; }
        public Nullable<int> Groupdeliverynumber { get; set; }
        public string PA_Ownerid { get; set; }
        public bool Internal { get; set; }
        public string Contactname { get; set; }
        public bool Email { get; set; }
        public bool Customernotification { get; set; }
        public bool Missinglogo { get; set; }
        public string UIProjectID { get; set; }
        public string KeywordRTVTitle { get; set; }
        public bool EmailCustomer { get; set; }
    
        public virtual Codespec Codespec { get; set; }
        public virtual Codespec Codespec1 { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFileMove> OrderFileMove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderfilesend> Orderfilesend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderIdAsText> OrderIdAsText { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialMediaArticle> SocialMediaArticle { get; set; }
        public virtual SocialMediaReportType SocialMediaReportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordersendingschedule> Ordersendingschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordersubscription> Ordersubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordertotal> Ordertotal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productionflyers> Productionflyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Userorder> Userorder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialMediaReport> SocialMediaReport { get; set; }
    }
}
