//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVMedia
    {
        public Nullable<int> JumboPilotID { get; set; }
        public long MediaID { get; set; }
        public string MediaName { get; set; }
        public string WebSite { get; set; }
        public bool Active { get; set; }
        public Nullable<long> MapMediaTypeID { get; set; }
        public Nullable<bool> MapMediaTypeActive { get; set; }
        public string MapMediaTypeDE { get; set; }
        public string MapMediaTypeEN { get; set; }
        public string MapMediaTypeNL { get; set; }
        public string MapMediaTypeFR { get; set; }
        public Nullable<long> MapFormatID { get; set; }
        public string MapFormatFR { get; set; }
        public string MapFormatNL { get; set; }
        public string MapFormatEN { get; set; }
        public string MapFormatDE { get; set; }
        public Nullable<bool> MapFormatActive { get; set; }
        public Nullable<long> MapPeriodicityID { get; set; }
        public string MapPeriodicityFR { get; set; }
        public string MapPeriodicityNL { get; set; }
        public string MapPeriodicityEN { get; set; }
        public string MapPeriodicityDE { get; set; }
        public Nullable<bool> MapPeriodicityActive { get; set; }
        public string MapCategoryFR { get; set; }
        public string MapCategoryNL { get; set; }
        public string MapCategoryEN { get; set; }
        public string MapCategoryDE { get; set; }
        public Nullable<bool> MapCategoryActive { get; set; }
        public string MapMediaTypeJumboPilotID { get; set; }
        public Nullable<long> MapCategoryID { get; set; }
        public string MapFormatJumboPilotID { get; set; }
        public string MapCategoryJumboPilotID { get; set; }
        public string MapPeriodicityJumboPilotID { get; set; }
        public Nullable<long> MapCountryID { get; set; }
        public string MapCountryFR { get; set; }
        public string MapCountryNL { get; set; }
        public string MapCountryEN { get; set; }
        public string MapCountryDE { get; set; }
        public string MapCountryJumboPilotID { get; set; }
        public Nullable<bool> DigitalRights { get; set; }
        public string MapLanguageFR { get; set; }
        public string MapLanguageNL { get; set; }
        public string MapLanguageEN { get; set; }
        public string MapLanguageDE { get; set; }
        public Nullable<int> Tirage { get; set; }
        public Nullable<long> ParentID { get; set; }
    }
}
