//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTask
    {
        public long ProjectTaskID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> TaskID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
    }
}
