//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sendingprice
    {
        public int Sendingpriceid { get; set; }
        public string TE_Sendingtypeid { get; set; }
        public Nullable<decimal> Percentagecostpost { get; set; }
        public string Sendingtext { get; set; }
        public Nullable<decimal> Fixedprice { get; set; }
        public Nullable<decimal> Pageprice { get; set; }
        public Nullable<decimal> Emailprice { get; set; }
    
        public virtual Codespec Codespec { get; set; }
    }
}
