//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataCustomer.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVMediaFigure
    {
        public long MediaFigureID { get; set; }
        public long MediaID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> Circulation { get; set; }
        public Nullable<int> Audience { get; set; }
    }
}
